packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  vite: 'npm:@voidzero-dev/vite-plus-core@0.2.4'
  vite-plus: 0.2.4
  vue: 3.5.39
  '@vitejs/plugin-vue': 6.0.7
  typescript: 6.0.3
  cesium: 1.143.0
  '@babylonjs/core': 9.16.1
